In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter

In [16]:
x = pd.read_csv('Diabetes_XTrain.csv')
y = pd.read_csv('Diabetes_YTrain.csv')

x = x.values
y = y.values
y = y.reshape((-1,))
x.shape

(576, 8)

In [17]:
xtest = pd.read_csv('Diabetes_Xtest.csv')
xtest = xtest.values

In [18]:
def dist(x1,x2):
    return np.sqrt(sum((x1-x2)**2))

# Test Time 
def knn(X,Y,queryPoint,k=5):
    
    vals = []
    m = X.shape[0]
    
    for i in range(m):
        d = dist(queryPoint,X[i])
        vals.append((d,Y[i]))
        
    
    vals = sorted(vals)
    # Nearest/First K points
    vals = vals[:k]
    
    vals = np.array(vals)
    
    #print(vals)
    
    new_vals = np.unique(vals[:,1],return_counts=True)
    print(new_vals)
    
    index = new_vals[1].argmax()
    pred = new_vals[0][index]
    
    return pred
    
    
    

In [22]:
for i in range(xtest.shape[0]):
    print(knn(x,y,xtest[i]))

(array([0., 1.]), array([2, 3], dtype=int64))
1.0
(array([0., 1.]), array([4, 1], dtype=int64))
0.0
(array([0.]), array([5], dtype=int64))
0.0
(array([0.]), array([5], dtype=int64))
0.0
(array([0.]), array([5], dtype=int64))
0.0
(array([0., 1.]), array([2, 3], dtype=int64))
1.0
(array([0., 1.]), array([1, 4], dtype=int64))
1.0
(array([0., 1.]), array([2, 3], dtype=int64))
1.0
(array([0.]), array([5], dtype=int64))
0.0
(array([0., 1.]), array([2, 3], dtype=int64))
1.0
(array([1.]), array([5], dtype=int64))
1.0
(array([0.]), array([5], dtype=int64))
0.0
(array([1.]), array([5], dtype=int64))
1.0
(array([0.]), array([5], dtype=int64))
0.0
(array([0., 1.]), array([3, 2], dtype=int64))
0.0
(array([0.]), array([5], dtype=int64))
0.0
(array([0., 1.]), array([4, 1], dtype=int64))
0.0
(array([0., 1.]), array([1, 4], dtype=int64))
1.0
(array([0., 1.]), array([1, 4], dtype=int64))
1.0
(array([1.]), array([5], dtype=int64))
1.0
(array([0., 1.]), array([3, 2], dtype=int64))
0.0
(array([0., 1.]), ar

(array([0., 1.]), array([3, 2], dtype=int64))
0.0
(array([0., 1.]), array([1, 4], dtype=int64))
1.0
(array([0., 1.]), array([3, 2], dtype=int64))
0.0
(array([0., 1.]), array([1, 4], dtype=int64))
1.0
(array([0., 1.]), array([2, 3], dtype=int64))
1.0
(array([0.]), array([5], dtype=int64))
0.0
